### PR TITLE
Don't #[allow(type_alias_bounds)].

### PR DESCRIPTION
**Pull request by eddyb**
https://github.com/rust-lang/rust/pull/54090 will fix false positives (maybe relevant?) and make it an error in the upcoming Rust 2018 edition, which means that if you want to migrate to Rust 2018, it shouldn't be ignored.

See also https://github.com/rust-lang/rust/issues/49441#issuecomment-421136550 for the decision and some background.

### CODE REVIEW

**Comment by eddyb** [comment]
I'm confused, what happened here?
Sadly, the type alias changes didn't make it into Rust 2018 but they should probably be revived at some point.

**Comment by antoyo** [comment]
Actually, I completely forgot about this PR. Sorry about that.
I'm not even sure why it was closed (maybe because I force pushed).
I guess I'll fix it when it becomes an error.

**Comment by eddyb** [comment]
It won't be an error in this case, I think it's a false positive warning right now, so the warning would just go away. For the record, this was the entire diff:
```diff
diff --git a/tiger/src/gen.rs b/tiger/src/gen.rs
index e3793be..56b2516 100644
--- a/tiger/src/gen.rs
+++ b/tiger/src/gen.rs
@@ -57,7 +57,6 @@ use ir::Statement::{
 };
 use temp::{Label, Temp};
 
-#[allow(type_alias_bounds)]
 pub type Access<F: Frame> = (Level<F>, F::Access);
 
 #[derive(Clone)]
```

**Comment by eddyb** [comment]
I just tried to push an updated version and GitHub won't let me reuse this PR.
Oh well, the diff is trivial.

**Pull request closed without merging**
